spring.application.name=DDA
spring.thymeleaf.cache=false

# Conexión a MySQL (XAMPP / phpMyAdmin)
spring.datasource.url=jdbc:mysql://localhost:3306/obligatoriodda?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openai.api.key=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

