spring.application.name=DDA
spring.thymeleaf.cache=false

# Conexión a MySQL (XAMPP / phpMyAdmin)
spring.datasource.url=jdbc:mysql://localhost:3306/obligatoriodda?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openai.api.key=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

